[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "csv-validator"
version = "0.1.0"
description = "CSV Validator CLI tool"
authors = [{ name = "QA Student" }]
dependencies = ["pandas"]

[tool.setuptools.packages.find]
where = ["."]
